default: &default
  adapter: postgresql
  pool: <%= Secrets.fetch(:database, :max_connections) %>
  encoding: <%= Secrets.fetch(:database, :encoding) %>
  database: <%= Secrets.fetch(:database, :name) %>
  username: <%= Secrets.fetch(:database, :user) %>
  password: <%= Secrets.fetch(:database, :password) %>
  host: <%= Secrets.fetch(:database, :host) %>
  port: <%= Secrets.fetch(:database, :port) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
