default: &default
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>
  serve_static_files: <%= ENV.fetch('SERVE_STATIC_FILES') == 'true' %>

  database:
    max_connections: <%= ENV.fetch('DATABASE_MAX_CONNECTIONS') %>
    name: <%= ENV.fetch('DATABASE_NAME') %>
    user: <%= ENV.fetch('DATABASE_USERNAME') %>
    password: <%= ENV.fetch('DATABASE_PASSWORD') %>
    host: <%= ENV.fetch('DATABASE_HOST') %>
    port: <%= ENV.fetch('DATABASE_PORT') %>
    encoding: <%= ENV.fetch('DATABASE_ENCODING') %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
